main: me.flaming.PluginMain
name: OptimisedHoppers
version: 1.0
api-version: 1.19
commands:
  optimisedhoppers:
    description: Optimised Hoppers commands
    permission: optimisedhoppers.usecommands
    permission-message: You do not have the permission to use this command.
    aliases:
      - oh